Tiss_HealthQuestionnaire/Models/CognitiveScreening.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CognitiveScreening
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public Nullable<int> AnswerOption1 { get; set; }
        public Nullable<int> AnswerOption2 { get; set; }
    }
}

Tiss_HealthQuestionnaire/Models/Concentration.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concentration
    {
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string ListA { get; set; }
        public string ListB { get; set; }
        public string ListC { get; set; }
    }
}

Tiss_HealthQuestionnaire/Models/CoordinationAndBalanceExamination.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinationAndBalanceExamination
    {
        public int ExaminationID { get; set; }
        public string TestFoot { get; set; }
        public string TestSurface { get; set; }
        public string Footwear { get; set; }
    }
}

Tiss_HealthQuestionnaire/Models/DelayedRecall.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelayedRecall
    {
        public int ID { get; set; }
        public string Word { get; set; }
        public int Score0 { get; set; }
        public int Score1 { get; set; }
    }
}

Tiss_HealthQuestionnaire/Models/ImmediateMemory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImmediateMemory
    {
        public int ID { get; set; }
        public string Word { get; set; }
        public int FirstTest { get; set; }
        public int SecondTest { get; set; }
        public int ThirdTest { get; set; }
    }
}

Tiss_HealthQuestionnaire/Models/OrthopaedicScreening.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrthopaedicScreening
    {
        public int Id { get; set; }
        public string Instructions { get; set; }
        public string ObservationPoints { get; set; }
        public string ResultNormal { get; set; }
        public string ResultAbnormal { get; set; }
    }
}

Tiss_HealthQuestionnaire/Controllers/MedicalEvaluationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tiss_HealthQuestionnaire.Models;

namespace Tiss_HealthQuestionnaire.Controllers
{
    public class MedicalEvaluationController : BaseAuthController
    {
        protected override string[] AllowedRoles => new[] { "trainer"};

        private HealthQuestionnaireEntities _db = new HealthQuestionnaireEntities();

        #region 醫療團隊評估主頁
        public ActionResult ConcussionMedicalEvaluation()
        {
            try
            {
                if (Session["UserRole"] == null || Session["UserRole"].ToString() != "trainer")
                {
                    return RedirectToAction("Login", "Account", new { role = "trainer" });
                }

                var model = new MedicalViewModel
                {
                    CognitiveStepStatus = new CognitiveStepStatusViewModel
                    {
                        Step1Completed = Session["OrientationScore"] != null,
                        Step2Completed = Session["ImmediateMemoryScore"] != null,
                        Step3Completed = Session["ConcentrationScore"] != null,
                        Step4Completed = Session["CoordinationError"] != null,
                        Step5Completed = Session["DelayedRecallTotalScore"] != null,
                        Step6Completed = Session["CognitiveScreeningTotalScores"] != null
                    }
                };

                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 醫療團隊評估-腦震盪篩檢-認知篩檢-定位(1)
        public ActionResult CognitiveScreening()
        {
            try
            {
                var questions = _db.CognitiveScreening.ToList();

                var model = new MedicalViewModel
                {
                    CognitiveScreeningItems = questions
                };

                Session["CognitiveScreeningItems"] = questions;

                return View("CognitiveScreening", model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult CognitiveScreening(FormCollection form)
        {
            try
            {
                var questions = Session["CognitiveScreeningItems"] as List<CognitiveScreening>;
                int totalScore = 0;

                foreach (var item in questions)
                {
                    string key = $"question_{item.ID}";
                    int score = form[key] == "1" ? 1 : 0;
                    item.AnswerOption1 = score;
                    totalScore += score;
                }

                Session["OrientationScore"] = totalScore;
                Session["CognitiveScreeningItems"] = questions;

                return RedirectToAction("ImmediateMemory");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 醫療團隊評估-腦震盪篩檢-認知篩檢-短期記憶(2)
        public ActionResult ImmediateMemory()
        {
            try
            {
                var items = _db.ImmediateMemory.ToList();

                var viewModels = items.Select((x, i) => new ImmediateMemoryViewModel
                {
                    ID = i + 1,
                    Word = x.Word,
                    FirstTestScore = x.FirstTest,
                    SecondTestScore = x.SecondTest,
                    ThirdTestScore = x.ThirdTest
                }).ToList();

                var model = new MedicalViewModel
                {
                    ImmediateMemoryItems = viewModels,
                    ImmediateMemoryTotalScore = Convert.ToInt32(Session["ImmediateMemoryScore"] ?? 0),
                    CompletionTime = Session["CompletionTime"]?.ToString() ?? "00:00"
                };

                return View("ImmediateMemory", model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult ImmediateMemory(FormCollection form)
        {
            try
            {
                int total = 0;
                var items = _db.ImmediateMemory.ToList();

                var viewModels = items.Select((item, i) =>
                {
                    int f = int.Parse(form[$"first_{item.ID}"] ?? "0");
                    int s = int.Parse(form[$"second_{item.ID}"] ?? "0");
                    int t = int.Parse(form[$"third_{item.ID}"] ?? "0");

                    total += f + s + t;

                    return new ImmediateMemoryViewModel
                    {
                        ID = item.ID,
                        Word = item.Word,
                        FirstTestScore = f,
                        SecondTestScore = s,
                        ThirdTestScore = t
                    };
                }).ToList();

                Session["ImmediateMemoryScore"] = total;
                Session["CompletionTime"] = form["CompletionTime"] ?? "00:00";
                Session["ImmediateMemoryItems"] = viewModels;

                return RedirectToAction("Concentration");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 醫療團隊評估-腦震盪篩檢-認知篩檢-專注力(3)
        public ActionResult Concentration()
        {
            try
            {
                var items = _db.Concentration.ToList();

                var viewModels = items.Select((x, i) => new ConcentrationViewModel
                {
                    ID = i + 1,
                    ListA = x.ListA,
                    ListB = x.ListB,
                    ListC = x.ListC,
                    Score = 0 // 預設為 0
                }).ToList();

                var model = new MedicalViewModel
                {
                    ConcentrationItems = viewModels
                };

                Session["ConcentrationItems"] = viewModels;
                return View("Concentration", model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Concentration(FormCollection form)
        {
            try
            {
                var questions = Session["ConcentrationItems"] as List<ConcentrationViewModel>;
                int total = 0;

                foreach (var item in questions)
                {
                    string key = $"response_{item.ID}";
                    int score = form[key] == "1" ? 1 : 0;
                    item.Score = score;
                    total += score;
                }

                Session["ConcentrationScore"] = total;
                Session["ConcentrationItems"] = questions;

                return RedirectToAction("CoordinationAndBalanceExamination");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 醫療團隊評估-腦震盪篩檢-認知篩檢-協調與平衡測驗(4)
        public ActionResult CoordinationAndBalanceExamination()
        {
            try
            {
                var model = new MedicalViewModel
                {
                    CoordinationAndBalanceItems = new List<CoordinationAndBalanceExaminationViewModel>
                    {
                        new CoordinationAndBalanceExaminationViewModel()
                    }
                };

                return View("CoordinationAndBalanceExamination", model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult CoordinationAndBalanceExamination(FormCollection form)
        {
            try
            {
                var errors = new CoordinationAndBalanceExaminationViewModel
                {
                    TestFoot = form["TestFoot"],
                    TestSurface = form["TestSurface"],
                    Footwear = form["Footwear"],
                    DoubleLegError = int.Parse(form["DoubleLegError"] ?? "0"),
                    TandemError = int.Parse(form["TandemError"] ?? "0"),
                    SingleLegError = int.Parse(form["SingleLegError"] ?? "0"),
                    FirstTime = float.Parse(form["FirstTime"] ?? "0"),
                    SecondTime = float.Parse(form["SecondTime"] ?? "0"),
                    ThirdTime = float.Parse(form["ThirdTime"] ?? "0")
                };

                errors.TotalErrors = errors.DoubleLegError + errors.TandemError + errors.SingleLegError;
                errors.AverageTimes = (errors.FirstTime + errors.SecondTime + errors.ThirdTime) / 3;
                errors.FastestTimes = Math.Min(errors.FirstTime, Math.Min(errors.SecondTime, errors.ThirdTime));

                Session["CoordinationError"] = errors.TotalErrors;
                Session["CoordinationAvg"] = errors.AverageTimes;
                Session["CoordinationFast"] = errors.FastestTimes;
                Session["CoordinationItems"] = new List<CoordinationAndBalanceExaminationViewModel> { errors };

                return RedirectToAction("DelayedRecall");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 醫療團隊評估-腦震盪篩檢-認知篩檢-延遲記憶(5)
        public ActionResult DelayedRecall()
        {
            try
            {
                var items = _db.DelayedRecall.ToList();

                var viewModels = items.Select((x, i) => new DelayedRecallViewModel
                {
                    ID = i + 1,
                    Word = x.Word,
                    Score = x.Score1
                }).ToList();

                var model = new MedicalViewModel
                {
                    DelayedRecallItems = viewModels,

Tiss_HealthQuestionnaire/Views/MedicalEvaluation/CognitiveScreening.cshtml
@model Tiss_HealthQuestionnaire.Models.MedicalViewModel
@{
    Layout = "~/Views/Shared/_HealthLayout.cshtml";
}
<div class="container mx-auto px-4 py-6">
    <div class="bg-white rounded-lg shadow-md p-6">
        <h1 class="text-2xl font-bold text-gray-800 mb-4">1. 認知篩檢 - 定位(Cognitive Screening)</h1>
        <p class="text-gray-600 mb-6">請根據選手對下列問題的回答，選擇是否正確。</p>
        <form method="post" action="@Url.Action("CognitiveScreening", "MedicalEvaluation")">
            <div class="overflow-x-auto">
                <table class="min-w-full bg-white border border-gray-300 text-center">
                    <thead>
                        <tr class="bg-gray-100">
                            <th class="border border-gray-300 px-4 py-2">項次</th>
                            <th class="border border-gray-300 px-4 py-2">問題</th>
                            <th class="border border-gray-300 px-4 py-2">0 (錯誤)</th>
                            <th class="border border-gray-300 px-4 py-2">1 (正確)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.CognitiveScreeningItems)
                        {
                            <tr class="hover:bg-gray-50">
                                <td class="border border-gray-300 px-4 py-2">@item.ID</td>
                                <td class="border border-gray-300 px-4 py-2 text-left">@item.Question</td>
                                <td class="border border-gray-300 px-4 py-2">
                                    <input type="radio" class="form-radio h-5 w-5 score-option" name="question_@item.ID" value="0" />
                                </td>
                                <td class="border border-gray-300 px-4 py-2">
                                    <input type="radio" class="form-radio h-5 w-5 score-option" name="question_@item.ID" value="1" />
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="flex items-center mt-6">
                <span class="mr-2 text-lg font-semibold text-gray-700">定位總分：</span>
                <span id="totalScore" class="text-xl font-bold text-blue-600">0</span>
                <span class="ml-2 text-gray-600">/ @Model.CognitiveScreeningItems.Count()</span>
            </div>

            <div class="mt-6">
                <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-6 rounded shadow">
                    下一題
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    function initializeOrientation() {
        const scoreKey = 'OrientationScore';

        loadScores();

        $('.score-option').on('change', function () {
            updateTotalScore();
            saveScores();
        });

        function updateTotalScore() {
            let totalScore = 0;
            $('input[type="radio"]:checked').each(function () {
                const value = parseInt($(this).val(), 10);
                if (!isNaN(value)) {
                    totalScore += value;
                }
            });

            $('#totalScore').text(totalScore);
            sessionStorage.setItem(scoreKey, totalScore);
        }

        function saveScores() {
            $('input[type="radio"]').each(function () {
                if ($(this).is(':checked')) {
                    sessionStorage.setItem($(this).attr('name'), $(this).val());
                }
            });
        }

        function loadScores() {
            $('input[type="radio"]').each(function () {
                const savedValue = sessionStorage.getItem($(this).attr('name'));
                if (savedValue !== null) {
                    $(this).filter(`[value="${savedValue}"]`).prop("checked", true);
                }
            });

            updateTotalScore();
        }
    }

    document.addEventListener("DOMContentLoaded", initializeOrientation);
</script>

Tiss_HealthQuestionnaire/Views/MedicalEvaluation/CognitiveScreeningTotalScore.cshtml
@model Tiss_HealthQuestionnaire.Models.MedicalViewModel
@{
    Layout = "~/Views/Shared/_HealthLayout.cshtml";
}
@using (Html.BeginForm("TrainerPreview", "MedicalEvaluation", FormMethod.Post))
{
    <div class="container mx-auto px-4 py-6">
        <div class="bg-white rounded-lg shadow-md p-6">
            <h1 class="text-2xl font-bold text-blue-800 mb-4">6. 認知篩檢分數總合</h1>

            <table class="min-w-full border border-gray-300 text-center rounded">
                <thead class="bg-gray-100 font-semibold">
                    <tr>
                        <th class="border px-4 py-2">項目</th>
                        <th class="border px-4 py-2">分數</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="border px-4 py-2">定位 (Orientation)</td>
                        <td class="border px-4 py-2">@Model.CognitiveScreeningTotalScore / 5</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2">短期記憶 (Immediate Memory)</td>
                        <td class="border px-4 py-2">@Model.ImmediateMemoryTotalScore / 30</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2">專注力 (Concentration)</td>
                        <td class="border px-4 py-2">@Model.ConcentrationTotalScore / 4</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2">協調與平衡 (Coordination)</td>
                        <td class="border px-4 py-2">
                            @(30 - Model.CoordinationAndBalanceTotalErrors < 0 ? 0 : 30 - Model.CoordinationAndBalanceTotalErrors) / 30
                        </td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2">延遲記憶 (Delayed Recall)</td>
                        <td class="border px-4 py-2">@Model.DelayedRecallTotalScore / 10</td>
                    </tr>
                    <tr class="bg-gray-100 font-bold">
                        <td class="border px-4 py-2">總分</td>
                        <td class="border px-4 py-2">@Model.CognitiveScreeningTotalScores / 79</td>
                    </tr>
                </tbody>
            </table>

            @Html.Hidden("OrientationScore", Model.CognitiveScreeningTotalScore)
            @Html.Hidden("ImmediateMemoryScore", Model.ImmediateMemoryTotalScore)
            @Html.Hidden("CompletionTime", Model.CompletionTime)
            @Html.Hidden("ConcentrationScore", Model.ConcentrationTotalScore)
            @Html.Hidden("CoordinationError", Model.CoordinationAndBalanceTotalErrors)
            @Html.Hidden("CoordinationAverageTime", Model.CoordinationAndBalanceAverageTime)
            @Html.Hidden("CoordinationFastestTime", Model.CoordinationAndBalanceFastestTime)
            @Html.Hidden("DelayedRecallTotalScore", Model.DelayedRecallTotalScore)
            @Html.Hidden("CognitiveScreeningTotalScores", Model.CognitiveScreeningTotalScores)

            <div class="mt-6 flex justify-between">
                <a href="@Url.Action("ConcussionMedicalEvaluation", "MedicalEvaluation")"
                   class="bg-gray-600 hover:bg-gray-700 text-white font-semibold px-6 py-2 rounded shadow">
                    回到醫療團隊評估主頁
                </a>

                <button type="submit"
                        class="bg-green-600 hover:bg-green-700 text-white font-semibold px-6 py-2 rounded shadow">
                    前往預覽頁
                </button>
            </div>
        </div>
    </div>
}

Tiss_HealthQuestionnaire/Views/MedicalEvaluation/Concentration.cshtml
@model Tiss_HealthQuestionnaire.Models.MedicalViewModel
@{
    Layout = "~/Views/Shared/_HealthLayout.cshtml";
}
<div class="container mx-auto px-4 py-6">
    <div class="bg-white rounded-lg shadow-md p-6">
        <h1 class="text-2xl font-bold text-blue-800 mb-4">3. 專注力 (Concentration)</h1>
        <p class="text-gray-700 mb-6">請依據下列數列判斷是否為倒數排列，勾選 Y（正確）或 N（錯誤）。</p>

        <form method="post" action="@Url.Action("Concentration", "MedicalEvaluation")">
            <div class="overflow-x-auto">
                <table class="min-w-full border border-gray-300 text-center rounded">
                    <thead class="bg-gray-100">
                        <tr>
                            <th class="border px-4 py-2">List A</th>
                            <th class="border px-4 py-2">List B</th>
                            <th class="border px-4 py-2">List C</th>
                            <th class="border px-4 py-2">Y</th>
                            <th class="border px-4 py-2">N</th>
                            <th class="border px-4 py-2">得分</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ConcentrationItems)
                        {
                            <tr class="hover:bg-gray-50">
                                <td class="border px-4 py-2">@item.ListA</td>
                                <td class="border px-4 py-2">@item.ListB</td>
                                <td class="border px-4 py-2">@item.ListC</td>
                                <td class="border px-4 py-2">
                                    <input type="radio" name="response_@item.ID" value="1" class="form-radio h-5 w-5 concentration-option"> Y
                                </td>
                                <td class="border px-4 py-2">
                                    <input type="radio" name="response_@item.ID" value="0" class="form-radio h-5 w-5 concentration-option"> N
                                </td>
                                <td class="border px-4 py-2" id="score_@item.ID">0</td>
                            </tr>
                        }
                    </tbody>
                    <tfoot class="bg-gray-100 font-semibold">
                        <tr>
                            <td colspan="5" class="text-right border px-4 py-2">總分</td>
                            <td class="border px-4 py-2" id="totalScore">0 / @Model.ConcentrationItems.Count()</td>
                        </tr>
                    </tfoot>
                </table>
            </div>

            <div class="mt-6 text-right">
                <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded shadow">下一題</button>
            </div>
        </form>
    </div>
</div>

<script>
    function initializeConcentration() {
        const scoreKey = 'ConcentrationScore';

        loadScores();

        $('.concentration-option').on('change', function () {
            updateScores();
            saveScores();
        });

        function updateScores() {
            let totalScore = 0;
            $('.concentration-option:checked').each(function () {
                const value = parseInt($(this).val());
                const id = $(this).attr('name').split('_')[1];
                $(`#score_${id}`).text(value === 1 ? '1' : '0');
                totalScore += value;
            });
            $('#totalScore').text(`${totalScore} / ${$('.concentration-option').length / 2}`);
            sessionStorage.setItem(scoreKey, totalScore);
        }

        function saveScores() {
            $('input[type="radio"]').each(function () {
                if ($(this).is(':checked')) {
                    sessionStorage.setItem($(this).attr('name'), $(this).val());
                }
            });
        }

        function loadScores() {
            $('input[type="radio"]').each(function () {
                const savedValue = sessionStorage.getItem($(this).attr('name'));
                if (savedValue !== null && $(this).val() === savedValue) {
                    $(this).prop('checked', true);
                }
            });
            updateScores();
        }
    }

    document.addEventListener("DOMContentLoaded", initializeConcentration);
</script>

Tiss_HealthQuestionnaire/Views/MedicalEvaluation/DelayedRecall.cshtml
@model Tiss_HealthQuestionnaire.Models.MedicalViewModel
@{
    Layout = "~/Views/Shared/_HealthLayout.cshtml";
}
<div class="container mx-auto px-4 py-6">
    <div class="bg-white rounded-lg shadow-md p-6">
        <h1 class="text-2xl font-bold text-blue-800 mb-4">5. 延遲記憶 (Delayed Recall)</h1>
        <p class="mb-6 text-gray-700">請選手回想並複誦上述曾出現的詞彙，每題勾選「1」代表正確、勾選「0」代表錯誤。</p>

        <form method="post" action="@Url.Action("DelayedRecall", "MedicalEvaluation")">
            <div class="overflow-x-auto">
                <table class="min-w-full bg-white border border-gray-300 text-center rounded">
                    <thead class="bg-gray-100">
                        <tr>
                            <th class="border px-4 py-2">詞彙</th>
                            <th class="border px-4 py-2">分數</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.DelayedRecallItems)
                        {
                            <tr class="hover:bg-gray-50">
                                <td class="border px-4 py-2">@item.Word</td>
                                <td class="border px-4 py-2">
                                    <div class="flex justify-center gap-6">
                                        <label class="inline-flex items-center">
                                            <input type="radio" name="score_@item.ID" value="0" class="form-radio memory-option w-5 h-5">
                                            <span class="ml-1">0</span>
                                        </label>
                                        <label class="inline-flex items-center">
                                            <input type="radio" name="score_@item.ID" value="1" class="form-radio memory-option w-5 h-5">
                                            <span class="ml-1">1</span>
                                        </label>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot class="bg-gray-100 font-semibold">
                        <tr>
                            <td class="border px-4 py-2">總分</td>
                            <td class="border px-4 py-2">
                                <span id="totalScore">0</span> / @Model.DelayedRecallItems.Count()
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>

            <div class="mt-6 flex items-center gap-4">
                <label for="testStartTime" class="text-lg font-medium text-gray-700">📅測驗開始時間：</label>
                <input type="time" id="testStartTime" name="testStartTime" class="border border-gray-300 rounded px-3 py-1 w-36" value="@Model.testStartTimeDisplay">
            </div>

            <div class="mt-6 text-right">
                <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-semibold px-6 py-2 rounded shadow">
                    下一題（總分計算）
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    function initializeDelayedRecall() {
        const scoreKey = 'DelayedRecallTotalScore';
        const timeKey = 'DelayedRecallStartTime';

        loadScores();

        $('.memory-option').on('change', function () {
            updateTotalScore();
            saveScores();
        });

        $('#testStartTime').on('change', function () {
            saveScores();
        });

        function updateTotalScore() {
            let total = 0;
            $('.memory-option:checked').each(function () {
                total += parseInt($(this).val());
            });
            $('#totalScore').text(total);
            sessionStorage.setItem(scoreKey, total);
        }

        function saveScores() {
            $('.memory-option').each(function () {
                if ($(this).is(':checked')) {
                    sessionStorage.setItem($(this).attr('name'), $(this).val());
                }
            });
            const time = $('#testStartTime').val();
            sessionStorage.setItem(timeKey, time);
        }

        function loadScores() {
            $('.memory-option').each(function () {
                const val = sessionStorage.getItem($(this).attr('name'));
                if (val !== null && $(this).val() === val) {
                    $(this).prop('checked', true);
                }
            });

            const score = sessionStorage.getItem(scoreKey);
            if (score !== null) $('#totalScore').text(score);

            const savedTime = sessionStorage.getItem(timeKey);
            if (savedTime !== null) $('#testStartTime').val(savedTime);
        }
    }

    document.addEventListener("DOMContentLoaded", initializeDelayedRecall);
</script>